/* Leap: iPhone hardware + hardware-gated iOS features.
   Compiled from Apple spec pages and public reporting (Sept 2026).
   Unofficial; not affiliated with Apple. Region and language limits apply. */

(function (global) {
  function phone(base) {
    return Object.assign(
      {
        ram: 4,
        displayIn: 6.1,
        displayType: "oled",
        refresh: 60,
        peakNits: 625,
        face: "notch",
        faceId: true,
        touchId: false,
        connector: "Lightning",
        usb3: false,
        fiveG: false,
        magsafe: false,
        ceramicShield: 0,
        alwaysOn: false,
        proMotion: false,
        actionButton: false,
        cameraControl: false,
        appleIntelligence: false,
        satelliteSos: false,
        crashDetection: false,
        roadsideSatellite: false,
        satelliteMessages: false,
        lidar: false,
        ultraWide: false,
        telephoto: false,
        mainMp: 12,
        frontMp: 12,
        opticalZoom: "1×",
        cinematic: false,
        actionMode: false,
        spatialVideo: false,
        macro: false,
        nightMode: false,
        photonicEngine: false,
        photographicStyles: 0,
        centerStage: false,
        dualCapture: false,
        wifi: 5,
        uwb: 0,
        thread: false,
        mie: false,
        lastIos: 27,
        accent: "#8e8e93",
        variableAperture: false,
        foldable: false,
        dualDisplay: false,
        nanoTexture: false,
        smartTake: false,
        duoPreview: false,
        splitApps: false,
        applePencil: false,
        underDisplayCam: false,
        ceramicBack: false,
        dualNeural: false,
      },
      base
    );
  }

  const PHONES = [
    phone({
      id: "iphone-8",
      name: "iPhone 8",
      year: 2017,
      chip: "A11 Bionic",
      chipGen: 11,
      ram: 2,
      displayIn: 4.7,
      displayType: "lcd",
      peakNits: 625,
      face: "home",
      faceId: false,
      touchId: true,
      frontMp: 7,
      lastIos: 16,
      accent: "#c0c0c0",
    }),
    phone({
      id: "iphone-8-plus",
      name: "iPhone 8 Plus",
      year: 2017,
      chip: "A11 Bionic",
      chipGen: 11,
      ram: 3,
      displayIn: 5.5,
      displayType: "lcd",
      peakNits: 625,
      face: "home",
      faceId: false,
      touchId: true,
      telephoto: true,
      opticalZoom: "1× / 2×",
      frontMp: 7,
      lastIos: 16,
      accent: "#c0c0c0",
    }),
    phone({
      id: "iphone-x",
      name: "iPhone X",
      year: 2017,
      chip: "A11 Bionic",
      chipGen: 11,
      ram: 3,
      displayIn: 5.8,
      peakNits: 625,
      telephoto: true,
      opticalZoom: "1× / 2×",
      frontMp: 7,
      lastIos: 16,
      accent: "#1c1c1e",
    }),
    phone({
      id: "iphone-xr",
      name: "iPhone XR",
      year: 2018,
      chip: "A12 Bionic",
      chipGen: 12,
      ram: 3,
      displayIn: 6.1,
      displayType: "lcd",
      peakNits: 625,
      lastIos: 18,
      accent: "#5ac8fa",
    }),
    phone({
      id: "iphone-xs",
      name: "iPhone XS",
      year: 2018,
      chip: "A12 Bionic",
      chipGen: 12,
      telephoto: true,
      opticalZoom: "1× / 2×",
      lastIos: 18,
      accent: "#e8d5b5",
    }),
    phone({
      id: "iphone-xs-max",
      name: "iPhone XS Max",
      year: 2018,
      chip: "A12 Bionic",
      chipGen: 12,
      displayIn: 6.5,
      telephoto: true,
      opticalZoom: "1× / 2×",
      lastIos: 18,
      accent: "#e8d5b5",
    }),
    phone({
      id: "iphone-11",
      name: "iPhone 11",
      year: 2019,
      chip: "A13 Bionic",
      chipGen: 13,
      displayType: "lcd",
      peakNits: 625,
      ultraWide: true,
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#6e6e73",
    }),
    phone({
      id: "iphone-11-pro",
      name: "iPhone 11 Pro",
      year: 2019,
      chip: "A13 Bionic",
      chipGen: 13,
      displayIn: 5.8,
      peakNits: 800,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 2×",
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#2c2c2e",
    }),
    phone({
      id: "iphone-11-pro-max",
      name: "iPhone 11 Pro Max",
      year: 2019,
      chip: "A13 Bionic",
      chipGen: 13,
      displayIn: 6.5,
      peakNits: 800,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 2×",
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#2c2c2e",
    }),
    phone({
      id: "iphone-se-2020",
      name: "iPhone SE (2020)",
      year: 2020,
      chip: "A13 Bionic",
      chipGen: 13,
      ram: 3,
      displayIn: 4.7,
      displayType: "lcd",
      face: "home",
      faceId: false,
      touchId: true,
      wifi: 6,
      accent: "#d4a5a5",
    }),
    phone({
      id: "iphone-12-mini",
      name: "iPhone 12 mini",
      year: 2020,
      chip: "A14 Bionic",
      chipGen: 14,
      displayIn: 5.4,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#5e5ce6",
    }),
    phone({
      id: "iphone-12",
      name: "iPhone 12",
      year: 2020,
      chip: "A14 Bionic",
      chipGen: 14,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#64d2ff",
    }),
    phone({
      id: "iphone-12-pro",
      name: "iPhone 12 Pro",
      year: 2020,
      chip: "A14 Bionic",
      chipGen: 14,
      ram: 6,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 2×",
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#8e8e93",
    }),
    phone({
      id: "iphone-12-pro-max",
      name: "iPhone 12 Pro Max",
      year: 2020,
      chip: "A14 Bionic",
      chipGen: 14,
      ram: 6,
      displayIn: 6.7,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 2.5×",
      nightMode: true,
      wifi: 6,
      uwb: 1,
      accent: "#8e8e93",
    }),
    phone({
      id: "iphone-13-mini",
      name: "iPhone 13 mini",
      year: 2021,
      chip: "A15 Bionic",
      chipGen: 15,
      displayIn: 5.4,
      peakNits: 800,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      cinematic: true,
      nightMode: true,
      photographicStyles: 1,
      wifi: 6,
      uwb: 1,
      accent: "#bf5af2",
    }),
    phone({
      id: "iphone-13",
      name: "iPhone 13",
      year: 2021,
      chip: "A15 Bionic",
      chipGen: 15,
      peakNits: 800,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      cinematic: true,
      nightMode: true,
      photographicStyles: 1,
      wifi: 6,
      uwb: 1,
      accent: "#30d158",
    }),
    phone({
      id: "iphone-13-pro",
      name: "iPhone 13 Pro",
      year: 2021,
      chip: "A15 Bionic",
      chipGen: 15,
      ram: 6,
      peakNits: 1000,
      refresh: 120,
      proMotion: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 3×",
      cinematic: true,
      macro: true,
      nightMode: true,
      photographicStyles: 1,
      wifi: 6,
      uwb: 1,
      accent: "#a7c1b5",
    }),
    phone({
      id: "iphone-13-pro-max",
      name: "iPhone 13 Pro Max",
      year: 2021,
      chip: "A15 Bionic",
      chipGen: 15,
      ram: 6,
      displayIn: 6.7,
      peakNits: 1000,
      refresh: 120,
      proMotion: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      opticalZoom: "0.5× / 1× / 3×",
      cinematic: true,
      macro: true,
      nightMode: true,
      photographicStyles: 1,
      wifi: 6,
      uwb: 1,
      accent: "#a7c1b5",
    }),
    phone({
      id: "iphone-se-2022",
      name: "iPhone SE (2022)",
      year: 2022,
      chip: "A15 Bionic",
      chipGen: 15,
      displayIn: 4.7,
      displayType: "lcd",
      face: "home",
      faceId: false,
      touchId: true,
      fiveG: true,
      wifi: 6,
      accent: "#ff375f",
    }),
    phone({
      id: "iphone-14",
      name: "iPhone 14",
      year: 2022,
      chip: "A15 Bionic",
      chipGen: 15,
      ram: 6,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      cinematic: true,
      actionMode: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#3a6ea5",
    }),
    phone({
      id: "iphone-14-plus",
      name: "iPhone 14 Plus",
      year: 2022,
      chip: "A15 Bionic",
      chipGen: 15,
      ram: 6,
      displayIn: 6.7,
      peakNits: 1200,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      cinematic: true,
      actionMode: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#3a6ea5",
    }),
    phone({
      id: "iphone-14-pro",
      name: "iPhone 14 Pro",
      year: 2022,
      chip: "A16 Bionic",
      chipGen: 16,
      ram: 6,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 3×",
      cinematic: true,
      actionMode: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#4a4a4c",
    }),
    phone({
      id: "iphone-14-pro-max",
      name: "iPhone 14 Pro Max",
      year: 2022,
      chip: "A16 Bionic",
      chipGen: 16,
      ram: 6,
      displayIn: 6.7,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 3×",
      cinematic: true,
      actionMode: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#4a4a4c",
    }),
    phone({
      id: "iphone-15",
      name: "iPhone 15",
      year: 2023,
      chip: "A16 Bionic",
      chipGen: 16,
      ram: 6,
      peakNits: 2000,
      face: "island",
      connector: "USB-C",
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#c7f0d2",
    }),
    phone({
      id: "iphone-15-plus",
      name: "iPhone 15 Plus",
      year: 2023,
      chip: "A16 Bionic",
      chipGen: 16,
      ram: 6,
      displayIn: 6.7,
      peakNits: 2000,
      face: "island",
      connector: "USB-C",
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      uwb: 1,
      accent: "#c7f0d2",
    }),
    phone({
      id: "iphone-15-pro",
      name: "iPhone 15 Pro",
      year: 2023,
      chip: "A17 Pro",
      chipGen: 17,
      ram: 8,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 3×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6.5,
      uwb: 2,
      thread: true,
      accent: "#b8a99a",
    }),
    phone({
      id: "iphone-15-pro-max",
      name: "iPhone 15 Pro Max",
      year: 2023,
      chip: "A17 Pro",
      chipGen: 17,
      ram: 8,
      displayIn: 6.7,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 5×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 1,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6.5,
      uwb: 2,
      thread: true,
      accent: "#b8a99a",
    }),
    phone({
      id: "iphone-16e",
      name: "iPhone 16e",
      year: 2025,
      chip: "A18",
      chipGen: 18,
      ram: 8,
      peakNits: 800,
      face: "notch",
      connector: "USB-C",
      actionButton: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      mainMp: 48,
      opticalZoom: "1× / 2×",
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      accent: "#f2c1c1",
    }),
    phone({
      id: "iphone-16",
      name: "iPhone 16",
      year: 2024,
      chip: "A18",
      chipGen: 18,
      ram: 8,
      peakNits: 2000,
      face: "island",
      connector: "USB-C",
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      accent: "#3d4f9c",
    }),
    phone({
      id: "iphone-16-plus",
      name: "iPhone 16 Plus",
      year: 2024,
      chip: "A18",
      chipGen: 18,
      ram: 8,
      displayIn: 6.7,
      peakNits: 2000,
      face: "island",
      connector: "USB-C",
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      ultraWide: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      accent: "#3d4f9c",
    }),
    phone({
      id: "iphone-16-pro",
      name: "iPhone 16 Pro",
      year: 2024,
      chip: "A18 Pro",
      chipGen: 18.5,
      ram: 8,
      displayIn: 6.3,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 5×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      accent: "#8a8f7c",
    }),
    phone({
      id: "iphone-16-pro-max",
      name: "iPhone 16 Pro Max",
      year: 2024,
      chip: "A18 Pro",
      chipGen: 18.5,
      ram: 8,
      displayIn: 6.9,
      peakNits: 2000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 1,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      opticalZoom: "0.5× / 1× / 5×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      accent: "#8a8f7c",
    }),
    phone({
      id: "iphone-17e",
      name: "iPhone 17e",
      year: 2026,
      chip: "A19",
      chipGen: 19,
      ram: 8,
      peakNits: 800,
      face: "notch",
      connector: "USB-C",
      actionButton: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      mainMp: 48,
      opticalZoom: "1× / 2×",
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 6,
      mie: true,
      accent: "#f4b8c8",
    }),
    phone({
      id: "iphone-17",
      name: "iPhone 17",
      year: 2025,
      chip: "A19",
      chipGen: 19,
      ram: 8,
      displayIn: 6.3,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      ultraWide: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      centerStage: true,
      dualCapture: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#b7a0d9",
    }),
    phone({
      id: "iphone-air",
      name: "iPhone Air",
      year: 2025,
      chip: "A19 Pro",
      chipGen: 19.5,
      ram: 12,
      displayIn: 6.5,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "1× / 2×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      centerStage: true,
      dualCapture: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#d8dde6",
    }),
    phone({
      id: "iphone-17-pro",
      name: "iPhone 17 Pro",
      year: 2025,
      chip: "A19 Pro",
      chipGen: 19.5,
      ram: 12,
      displayIn: 6.3,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 8×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      centerStage: true,
      dualCapture: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#c45c26",
    }),
    phone({
      id: "iphone-17-pro-max",
      name: "iPhone 17 Pro Max",
      year: 2025,
      chip: "A19 Pro",
      chipGen: 19.5,
      ram: 12,
      displayIn: 6.9,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 8×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 2,
      centerStage: true,
      dualCapture: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#c45c26",
    }),
    phone({
      id: "iphone-18-pro",
      name: "iPhone 18 Pro",
      year: 2026,
      chip: "A20 Pro",
      chipGen: 20.5,
      ram: 12,
      displayIn: 6.3,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      ceramicBack: true,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 4× / 8×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 3,
      centerStage: true,
      dualCapture: true,
      variableAperture: true,
      dualNeural: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#4a1c28",
    }),
    phone({
      id: "iphone-18-pro-max",
      name: "iPhone 18 Pro Max",
      year: 2026,
      chip: "A20 Pro",
      chipGen: 20.5,
      ram: 12,
      displayIn: 6.9,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "island",
      connector: "USB-C",
      usb3: true,
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      ceramicBack: true,
      lidar: true,
      ultraWide: true,
      telephoto: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 4× / 8×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 3,
      centerStage: true,
      dualCapture: true,
      variableAperture: true,
      dualNeural: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#4a1c28",
    }),
    phone({
      id: "iphone-duo",
      name: "iPhone Duo",
      year: 2026,
      chip: "A20 Pro",
      chipGen: 20.5,
      ram: 12,
      displayIn: 7.6,
      peakNits: 3000,
      refresh: 120,
      proMotion: true,
      alwaysOn: true,
      face: "duo",
      faceId: false,
      touchId: true,
      connector: "USB-C",
      actionButton: true,
      cameraControl: true,
      appleIntelligence: true,
      fiveG: true,
      magsafe: true,
      ceramicShield: 2,
      ceramicBack: true,
      ultraWide: true,
      mainMp: 48,
      frontMp: 18,
      opticalZoom: "0.5× / 1× / 2×",
      cinematic: true,
      actionMode: true,
      spatialVideo: true,
      macro: true,
      nightMode: true,
      photonicEngine: true,
      photographicStyles: 3,
      centerStage: true,
      dualCapture: true,
      foldable: true,
      dualDisplay: true,
      nanoTexture: true,
      smartTake: true,
      duoPreview: true,
      splitApps: true,
      applePencil: true,
      underDisplayCam: true,
      dualNeural: true,
      satelliteSos: true,
      crashDetection: true,
      roadsideSatellite: true,
      satelliteMessages: true,
      wifi: 7,
      uwb: 2,
      thread: true,
      mie: true,
      accent: "#1c1c1e",
    }),
  ];

  const STORE = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/";

  function storeImage(id) {
    return STORE + id + "?wid=2000&hei=2000&fmt=jpeg&qlt=90";
  }

  const PRODUCT_PAIR = [
    "iphone-8",
    "iphone-8-plus",
    "iphone-x",
    "iphone-xr",
    "iphone-xs",
    "iphone-xs-max",
    "iphone-se-2020",
  ];

  const PRODUCT_PAD = [
    "iphone-14",
    "iphone-14-plus",
    "iphone-14-pro",
    "iphone-14-pro-max",
    "iphone-15",
    "iphone-15-plus",
    "iphone-15-pro",
    "iphone-15-pro-max",
    "iphone-16e",
    "iphone-16",
    "iphone-16-plus",
    "iphone-16-pro",
    "iphone-16-pro-max",
    "iphone-17e",
    "iphone-air",
  ];

  const PRODUCT_FAR = ["iphone-17"];

  const PRODUCT_TIGHT = [
    "iphone-12-pro",
    "iphone-12-pro-max",
    "iphone-14-pro",
    "iphone-14-pro-max",
    "iphone-15",
    "iphone-15-plus",
    "iphone-15-pro",
    "iphone-15-pro-max",
    "iphone-16",
    "iphone-16-plus",
    "iphone-16-pro",
    "iphone-16-pro-max",
    "iphone-16e",
    "iphone-17",
    "iphone-17e",
    "iphone-17-pro",
    "iphone-17-pro-max",
    "iphone-air",
    "iphone-18-pro",
    "iphone-18-pro-max",
    "iphone-duo",
  ];

  const IMAGES = {
    "iphone-8": storeImage("iphone8-gold-select-2018"),
    "iphone-8-plus": storeImage("iphone8-plus-gold-select-2018"),
    "iphone-x": storeImage("iphone-x-silver-select-2017"),
    "iphone-xr": storeImage("iphone-xs-gold-select-2018"),
    "iphone-xs": storeImage("iphone-xs-gold-select-2018"),
    "iphone-xs-max": storeImage("iphone-xs-max-gold-select-2018"),
    "iphone-11": storeImage("iphone11-green-select-2019"),
    "iphone-11-pro": storeImage("iphone-11-pro-select-2019"),
    "iphone-11-pro-max": storeImage("iphone-11-pro-max-select-2019"),
    "iphone-se-2020": storeImage("iphone-se-red-select-2020"),
    "iphone-12-mini": storeImage("iphone-12-mini-blue-select-2020"),
    "iphone-12": storeImage("iphone-12-blue-select-2020"),
    "iphone-12-pro": storeImage("iphone-12-pro-graphite-hero"),
    "iphone-12-pro-max": storeImage("iphone-12-pro-max-graphite-hero"),
    "iphone-13-mini": storeImage("iphone-13-mini-pink-select-2021"),
    "iphone-13": storeImage("iphone-13-pink-select-2021"),
    "iphone-13-pro": storeImage("iphone-13-pro-graphite-select"),
    "iphone-13-pro-max": storeImage("iphone-13-pro-max-graphite-select"),
    "iphone-se-2022": storeImage("iphone-se-midnight-select-202203"),
    "iphone-14": storeImage("iphone-14-finish-select-202209-6-1inch-blue"),
    "iphone-14-plus": storeImage("iphone-14-finish-select-202209-6-7inch-blue"),
    "iphone-14-pro": storeImage("iphone-14-pro-deeppurple-select"),
    "iphone-14-pro-max": storeImage("iphone-14-pro-max-deeppurple-select"),
    "iphone-15": storeImage("iphone-15-finish-select-202309-6-1inch-blue"),
    "iphone-15-plus": storeImage("iphone-15-plus-pink-select-202309"),
    "iphone-15-pro": storeImage("iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium"),
    "iphone-15-pro-max": storeImage("iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium"),
    "iphone-16e": storeImage("iphone-16e-finish-select-202502-white"),
    "iphone-16": storeImage("iphone-16-finish-select-202409-6-1inch-ultramarine"),
    "iphone-16-plus": storeImage("iphone-16-plus-ultramarine-select-202409"),
    "iphone-16-pro": storeImage("iphone-16-pro-finish-select-202409-6-3inch-naturaltitanium"),
    "iphone-16-pro-max": storeImage("iphone-16-pro-finish-select-202409-6-9inch-naturaltitanium"),
    "iphone-17e": storeImage("iphone-17e-finish-select-202603-white"),
    "iphone-17": storeImage("iphone-17-lavender-select-202509"),
    "iphone-air": storeImage("iphone-air-finish-select-202509-lightgold"),
    "iphone-17-pro": storeImage("iphone-17-pro-finish-select-202509"),
    "iphone-17-pro-max": storeImage("iphone-17-pro-max-finish-select-202509"),
    "iphone-18-pro": storeImage("iphone-18-pro-finish-select-black-202609"),
    "iphone-18-pro-max": storeImage("iphone-18-pro-max-finish-select-black-202609"),
    "iphone-duo": storeImage("iphone-duo-finish-select-202609"),
  };

  const MARKETING = {
    "iphone-18-pro": {
      src: "https://www.apple.com/v/iphone-18-pro/a/images/overview/aio/hero__elo7tt0mnqy6_large.jpg",
      alt: "iPhone 18 Pro in Burgundy, angled to show the Pro Fusion camera system",
    },
    "iphone-18-pro-max": {
      src: "https://www.apple.com/v/iphone-18-pro/a/images/overview/aio/hero__elo7tt0mnqy6_large.jpg",
      alt: "iPhone 18 Pro Max camera system in Burgundy",
    },
  };

  const A18 = "https://www.apple.com/v/iphone-18-pro/a/images/overview";
  const DUO = "https://www.apple.com/v/iphone-duo/a/images/overview";

  const FEATURE_IMAGES = {
    "apple-intelligence": { src: `${A18}/family/siri_ai_hero__b93zn5f7x4aa_large.jpg`, alt: "Siri AI and Apple Intelligence on iPhone 18 Pro" },
    "writing-tools": { src: `${A18}/family/siri-ai/write__cskm66rylaky_large.jpg`, alt: "Writing with Siri AI on iPhone" },
    "notification-summaries": { src: `${A18}/family/ios-apple-intelligence/suggestions__c87yzqqh490m_large.jpg`, alt: "Suggested actions in Messages and Mail" },
    "clean-up": { src: `${A18}/family/ios-apple-intelligence/clean_up__c4nkcvxq91me_large.jpg`, alt: "Clean Up in Photos on iPhone" },
    "genmoji-playground": { src: `${A18}/family/ios-apple-intelligence/image_playground__do3eby1zbe82_large.jpg`, alt: "Image Playground on iPhone" },
    "visual-intelligence": { src: `${A18}/family/siri-ai/siri_mode__fi0ng1mrbvu6_large.jpg`, alt: "Siri mode and Visual Intelligence in Camera" },
    "live-translation": { src: `${A18}/family/siri-ai/world_knowledge__gfbdm64gdrue_large.jpg`, alt: "Siri AI answering a question on iPhone" },
    "siri-apple-intelligence": { src: `${A18}/family/siri-ai/siri_ai_assistant__el1seyzgpv0i_large.jpg`, alt: "Siri AI conversation on iPhone" },
    "camera-control": { src: `${A18}/product-viewer/camera_control__f4t7iottmvyy_large.jpg`, alt: "Camera Control on the side of iPhone 18 Pro", fit: "contain" },
    "48mp": { src: `${A18}/highlights/main_camera_endframe__fcjfhs06rdme_large.jpg`, alt: "48MP Fusion Main camera on iPhone 18 Pro" },
    "ultra-wide": { src: `${A18}/pro-camera/control/ultra_wide__fuin4rf0dnyq_large.jpg`, alt: "Ultra Wide camera sample from iPhone 18 Pro" },
    "telephoto": { src: `${A18}/pro-camera/control/8x-zoom_endframe__ed8psayfjwqe_large.jpg`, alt: "Telephoto zoom on iPhone 18 Pro" },
    "macro": { src: `${A18}/pro-camera/control/ultra_wide__fuin4rf0dnyq_large.jpg`, alt: "Close-up Ultra Wide capture on iPhone" },
    "night-mode": { src: `${A18}/pro-video/low_light__b51d1dpc3xde_large.jpg`, alt: "Low-light video captured on iPhone 18 Pro" },
    "photonic-engine": { src: `${DUO}/camera/photonic__dghocclrer2a_large.jpg`, alt: "Photonic Engine photo processing" },
    "photographic-styles-2": { src: `${A18}/pro-camera/control/photographic_styles__ef8cg39z0q2q_large.jpg`, alt: "Photographic Styles in the Camera app" },
    "cinematic-mode": { src: `${DUO}/camera/cinematic__dj9gdk228tm6_large.jpg`, alt: "Cinematic mode on iPhone" },
    "action-mode": { src: `${A18}/pro-video/features__16r2b47nrpe2_large.jpg`, alt: "Pro video features on iPhone 18 Pro" },
    "spatial-video": { src: `${A18}/pro-video/pro_video_endframe__jo1bq7ocrka6_large.jpg`, alt: "Pro video capture on iPhone 18 Pro" },
    "lidar": { src: `${A18}/pro-camera/system/hero__elo7tt0mnqy6_large.jpg`, alt: "Pro Fusion camera system on iPhone 18 Pro", fit: "contain" },
    "center-stage-front": { src: `${A18}/pro-camera/control/center_stage__ecf4wpldlkcy_large.jpg`, alt: "Center Stage front camera on iPhone 18 Pro" },
    "dual-capture": { src: `${A18}/pro-video/dual_capture__cwiaeus8h002_large.jpg`, alt: "Dual Capture video on iPhone 18 Pro" },
    "oled": { src: `${A18}/battery/hero__elo7tt0mnqy6_large.jpg`, alt: "Super Retina display playing Apple TV on iPhone 18 Pro" },
    "pro-motion": { src: `${A18}/product-viewer/dynamic_island_endframe__edszr68pgo66_large.jpg`, alt: "Dynamic Island and ProMotion display on iPhone 18 Pro" },
    "always-on": { src: `${DUO}/product-stories/versatility/apps_standby__b0akmv815b1e_large.jpg`, alt: "Always-On StandBy on iPhone Duo" },
    "dynamic-island": { src: `${A18}/product-viewer/dynamic_island_endframe__edszr68pgo66_large.jpg`, alt: "Dynamic Island on iPhone 18 Pro" },
    "ceramic-shield-2": { src: `${A18}/product-viewer/durability__gluy1en01nqm_large.jpg`, alt: "Ceramic Shield durability on iPhone 18 Pro", fit: "contain" },
    "ceramic-shield": { src: `${A18}/product-viewer/durability__gluy1en01nqm_large.jpg`, alt: "Ceramic Shield on iPhone", fit: "contain" },
    "face-id": { src: `${A18}/product-viewer/dynamic_island_startframe__e29ujwo7xcwi_large.jpg`, alt: "TrueDepth camera and Dynamic Island on iPhone" },
    "action-button": { src: `${A18}/product-viewer/action_button__f9p8n5h9xk66_large.jpg`, alt: "Action button on iPhone 18 Pro", fit: "contain" },
    "usb-c": { src: `${A18}/battery/charge__eiv9d90t9zue_large.png`, alt: "USB-C charging on iPhone 18 Pro", fit: "contain" },
    "usb-3": { src: `${A18}/battery/charge__eiv9d90t9zue_large.png`, alt: "USB-C port on iPhone 18 Pro", fit: "contain" },
    "magsafe": { src: `${A18}/accessories/accessories__eq6jc5t9202u_large.jpg`, alt: "MagSafe accessories for iPhone 18 Pro" },
    "5g": { src: `${A18}/family/connectivity/esim__dybvr8oo5ro2_large.jpg`, alt: "Cellular connectivity on iPhone" },
    "wifi-7": { src: `${A18}/family/connectivity/esim__dybvr8oo5ro2_large.jpg`, alt: "Wireless connectivity on iPhone" },
    "uwb": { src: `${A18}/family/connectivity/find_my__epk4pm9szhci_large.jpg`, alt: "Find My precision finding on iPhone" },
    "thread": { src: `${A18}/family/connectivity/esim__dybvr8oo5ro2_large.jpg`, alt: "Home and wireless radios on iPhone" },
    "crash-detection": { src: `${A18}/family/connectivity/crash_detection__c458d3ugtcom_large.jpg`, alt: "Crash Detection on iPhone" },
    "satellite-sos": { src: `${A18}/family/connectivity/esos__8m299y5obzmq_large.jpg`, alt: "Emergency SOS via satellite on iPhone" },
    "satellite-messages": { src: `${A18}/family/connectivity/messages__e05v4dplbdea_large.jpg`, alt: "Messages via satellite on iPhone" },
    "roadside-satellite": { src: `${A18}/family/connectivity/roadside__bqugdgosuzci_large.jpg`, alt: "Roadside Assistance via satellite on iPhone" },
    "mie": { src: `${A18}/upgrader/a20_pro_chip__c6rba3bxjuc2_large_2x.jpg`, alt: "A20 Pro chip", fit: "contain" },
    "variable-aperture": { src: `${A18}/pro-camera/aperture/max_light__dlmrw5m29ssy_large.jpg`, alt: "Variable-aperture Fusion camera photo at maximum light" },
    "photographic-styles-3": { src: `${A18}/pro-camera/control/photographic_styles__ef8cg39z0q2q_large.jpg`, alt: "Photographic Styles 3 with texture and grain" },
    "dual-neural": { src: `${A18}/highlights/chip_endframe__lhkymtfv1uie_large.jpg`, alt: "A20 Pro chip in iPhone 18 Pro" },
    "foldable": { src: `${DUO}/design/design_hero__gczn1e74mwa6_large.jpg`, alt: "iPhone Duo folding open" },
    "dual-display": { src: `${DUO}/product-stories/immersive/hero-display_endframe__5jdq3w2xk362_large.jpg`, alt: "iPhone Duo inner Super Retina display" },
    "nano-texture": { src: `${DUO}/product-stories/immersive/hero__dbnzxlb3ia2q_large.jpg`, alt: "iPhone Duo inner display with nano-texture finish" },
    "split-apps": { src: `${DUO}/product-stories/versatility/apps_standby__b0akmv815b1e_large.jpg`, alt: "Two apps side by side on iPhone Duo" },
    "smart-take": { src: `${DUO}/camera/smart-take_endframe__fzy3ygxinq2y_large.jpg`, alt: "Smart Take capturing a group photo on iPhone Duo" },
    "duo-preview": { src: `${DUO}/camera/duo-preview_endframe__gmc0ch1ssfyy_large.jpg`, alt: "Duo Preview on the outer display" },
    "under-display-cam": { src: `${DUO}/highlights/display__bx48n0ntsgvm_large.jpg`, alt: "Uninterrupted inner display on iPhone Duo" },
    "apple-pencil": { src: `${DUO}/product-viewer/laptop__c7kl6vmsqd6q_large.jpg`, alt: "iPhone Duo in a laptop pose for notes and sketching" },
    "ceramic-back": { src: `${DUO}/highlights/highlights_durability_endframe__e2gc60lhc5me_large.jpg`, alt: "Ceramic Shield back on iPhone Duo", fit: "contain" },
  };

  const CATEGORIES = [
    { id: "intelligence", label: "Apple Intelligence & iOS", icon: "fa-wand-magic-sparkles" },
    { id: "camera", label: "Camera", icon: "fa-camera" },
    { id: "display", label: "Display & design", icon: "fa-display" },
    { id: "controls", label: "Buttons, charging & daily use", icon: "fa-toggle-on" },
    { id: "safety", label: "Safety", icon: "fa-life-ring" },
    { id: "connectivity", label: "Connectivity", icon: "fa-wifi" },
    { id: "security", label: "Security", icon: "fa-shield-halved" },
  ];

  const FEATURES = [
    {
      id: "apple-intelligence",
      name: "Apple Intelligence",
      category: "intelligence",
      icon: "fa-wand-magic-sparkles",
      weight: 100,
      blurb: "On-device writing tools, notification summaries, Clean Up in Photos, Genmoji, Image Playground, and a Siri that can use what’s on your screen.",
      why: "Needs the A17 Pro Neural Engine (or newer) and 8GB of RAM. A standard iPhone 15 and every older model are left out. This is silicon, not a software toggle.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "writing-tools",
      name: "Writing Tools",
      category: "intelligence",
      icon: "fa-pen-fancy",
      weight: 86,
      blurb: "Rewrite, proofread, and summarize text in Mail, Messages, Notes, and almost any app, without pasting into a chatbot.",
      why: "Part of Apple Intelligence. The language models run on A17 Pro and later.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "notification-summaries",
      name: "Notification & email summaries",
      category: "intelligence",
      icon: "fa-inbox",
      weight: 84,
      blurb: "Long threads and stacked alerts collapse into a sentence you can actually scan, plus Priority notifications that surface what matters.",
      why: "Apple Intelligence feature. Older chips can’t run the on-device summarizer Apple ships.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "clean-up",
      name: "Clean Up in Photos",
      category: "intelligence",
      icon: "fa-eraser",
      weight: 88,
      blurb: "Lift out photobombers, poles, and clutter from a shot you already took, like a Magic Eraser that lives in Photos.",
      why: "Apple Intelligence image model. It is not the same as the older markup tools on iPhone 13 or 14.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "genmoji-playground",
      name: "Genmoji & Image Playground",
      category: "intelligence",
      icon: "fa-icons",
      weight: 70,
      blurb: "Type a description and get a custom emoji, or generate images in Messages and Image Playground.",
      why: "Apple Intelligence generative models. Unavailable below A17 Pro.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "visual-intelligence",
      name: "Visual Intelligence",
      category: "intelligence",
      icon: "fa-eye",
      weight: 92,
      blurb: "Point the camera at a restaurant, plant, poster, or homework problem and ask what you’re looking at. Look up, translate, or act on it.",
      why: "Needs Apple Intelligence. On iPhone 16 and 17 (except the e models) you hold Camera Control; on 15 Pro, 16e, and 17e you assign it to the Action button, Lock Screen, or Control Center.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "live-translation",
      name: "Live Translation",
      category: "intelligence",
      icon: "fa-language",
      weight: 80,
      blurb: "Translate calls, FaceTime, and Messages as you go, with the heavier lifting happening on-device when it can.",
      why: "Apple Intelligence. Older iPhones can still use the Translate app, but not this system-wide live layer.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "siri-apple-intelligence",
      name: "Siri with on-screen awareness",
      category: "intelligence",
      icon: "fa-comments",
      weight: 78,
      blurb: "Ask Siri about what’s on the screen, chain requests, and hand harder questions to ChatGPT when you choose to.",
      why: "The rebuilt Siri is an Apple Intelligence feature. Classic Siri still exists on older phones; this one does not.",
      has: (p) => p.appleIntelligence,
    },
    {
      id: "camera-control",
      name: "Camera Control",
      category: "camera",
      icon: "fa-circle-dot",
      weight: 90,
      blurb: "A capacitive shutter on the side: click to shoot, slide to zoom or pick a style, press-and-hold for Visual Intelligence.",
      why: "Physical hardware added on iPhone 16 and 17 (not the e models). Software cannot add this button.",
      has: (p) => p.cameraControl,
    },
    {
      id: "48mp",
      name: "48MP Fusion main camera",
      category: "camera",
      icon: "fa-aperture",
      weight: 76,
      blurb: "Default 24MP shots with room to crop, plus a 2× optical-quality zoom from the main sensor. Night and indoor photos hold together much better.",
      why: "A larger sensor and a 48MP pipeline that started on iPhone 14 Pro and came to every 15 and later (except some e-camera cutdowns still use 48MP on the main).",
      has: (p) => p.mainMp >= 48,
    },
    {
      id: "ultra-wide",
      name: "Ultra Wide camera",
      category: "camera",
      icon: "fa-expand",
      weight: 62,
      blurb: "0.5× group shots, interiors, and landscapes without stepping back. On Pro models this lens is also how Macro works.",
      why: "A second rear camera. Single-camera phones (8, XR, SE, 16e, 17e, Air) cannot do this.",
      has: (p) => p.ultraWide,
    },
    {
      id: "telephoto",
      name: "Telephoto camera",
      category: "camera",
      icon: "fa-magnifying-glass-plus",
      weight: 64,
      blurb: "Real optical zoom for portraits, wildlife, and details across a room, not just a digital crop of the main camera.",
      why: "A dedicated telephoto lens, historically a Pro (and some Plus/Max) exclusive.",
      has: (p) => p.telephoto,
    },
    {
      id: "macro",
      name: "Macro photography",
      category: "camera",
      icon: "fa-leaf",
      weight: 58,
      blurb: "Autofocus down to a few centimeters: textures, food, insects, printed text. The camera hops to the Ultra Wide automatically.",
      why: "Needs an autofocus Ultra Wide with a short minimum focus distance (13 Pro and later Pros, plus iPhone 16 / 16 Plus).",
      has: (p) => p.macro,
    },
    {
      id: "night-mode",
      name: "Night mode",
      category: "camera",
      icon: "fa-moon",
      weight: 72,
      blurb: "Handheld low-light photos that look like you had a tripod. Once you have it, you stop thinking about flash.",
      why: "Sensor and ISP work that arrived with iPhone 11. SE and everything before 11 never got it.",
      has: (p) => p.nightMode,
    },
    {
      id: "photonic-engine",
      name: "Photonic Engine",
      category: "camera",
      icon: "fa-sun",
      weight: 55,
      blurb: "Deep Fusion applied earlier in the capture pipeline, so mid- and low-light photos keep texture in faces and fabric.",
      why: "Hardware + ISP path introduced with iPhone 14. Older phones can run Smart HDR, not this pipeline.",
      has: (p) => p.photonicEngine,
    },
    {
      id: "photographic-styles-2",
      name: "Next-generation Photographic Styles",
      category: "camera",
      icon: "fa-sliders",
      weight: 50,
      blurb: "Styles that apply while you shoot, not a filter slapped on later, so skin tone and sky stay consistent across a roll.",
      why: "The 16-and-later style engine is tied to the new camera pipeline. iPhone 13 to 15 have the first-generation styles.",
      has: (p) => p.photographicStyles >= 2,
    },
    {
      id: "cinematic-mode",
      name: "Cinematic mode",
      category: "camera",
      icon: "fa-clapperboard",
      weight: 52,
      blurb: "Video that racks focus between people like a movie camera, with the focus points editable after you shoot.",
      why: "Needs the A15 camera stack. Introduced on iPhone 13.",
      has: (p) => p.cinematic,
    },
    {
      id: "action-mode",
      name: "Action mode",
      category: "camera",
      icon: "fa-person-running",
      weight: 54,
      blurb: "Ultra-stable handheld video when you’re walking, biking, or chasing a kid. It crops in and locks the frame down.",
      why: "A video stabilizer path that arrived with iPhone 14. Not the same as regular cinematic or movie-mode stabilization.",
      has: (p) => p.actionMode,
    },
    {
      id: "spatial-video",
      name: "Spatial photos & video",
      category: "camera",
      icon: "fa-vr-cardboard",
      weight: 48,
      blurb: "Capture memories that have depth on Apple Vision Pro (and spatial-capable iPhones): the two-eye look, not a flat 2D clip.",
      why: "Needs a camera pair and capture pipeline Apple enabled on 15 Pro and most 16 / 17 models (not the e phones).",
      has: (p) => p.spatialVideo,
    },
    {
      id: "lidar",
      name: "LiDAR Scanner",
      category: "camera",
      icon: "fa-diagram-project",
      weight: 44,
      blurb: "Faster autofocus in the dark, better Night mode portraits, and more accurate room scans in Measure and third-party AR apps.",
      why: "A dedicated depth sensor on Pro models from iPhone 12 Pro onward.",
      has: (p) => p.lidar,
    },
    {
      id: "center-stage-front",
      name: "Center Stage front camera",
      category: "camera",
      icon: "fa-user-group",
      weight: 68,
      blurb: "An 18MP front camera that reframes the group as people walk in and out, so FaceTime and selfies stop chopping someone off.",
      why: "New front camera hardware starting with iPhone 17, including 18 Pro and iPhone Duo.",
      has: (p) => p.centerStage,
    },
    {
      id: "dual-capture",
      name: "Dual Capture video",
      category: "camera",
      icon: "fa-clapperboard",
      weight: 60,
      blurb: "Record the rear camera and your face at the same time, so reaction videos and travel logs don’t need a second phone.",
      why: "A camera-system feature Apple enabled with iPhone 17 and later, including Duo.",
      has: (p) => p.dualCapture,
    },
    {
      id: "oled",
      name: "OLED Super Retina display",
      category: "display",
      icon: "fa-display",
      weight: 66,
      blurb: "True blacks, higher contrast, and a panel that can do Always-On later. LCD iPhones (8, XR, 11, SE) look washed next to this.",
      why: "A different display panel. Software updates cannot turn an LCD into OLED.",
      has: (p) => p.displayType === "oled",
    },
    {
      id: "pro-motion",
      name: "ProMotion 120Hz",
      category: "display",
      icon: "fa-gauge-high",
      weight: 82,
      blurb: "Scrolling, games, and the keyboard feel attached to your finger. Once you use 120Hz, 60Hz feels sticky.",
      why: "An LTPO display with a variable 1 to 120Hz refresh. First on 13 Pro; on the standard iPhone starting with 17 (not 17e).",
      has: (p) => p.proMotion,
    },
    {
      id: "always-on",
      name: "Always-On display",
      category: "display",
      icon: "fa-clock",
      weight: 74,
      blurb: "Lock Screen widgets, the clock, and Live Activities stay visible at a glance. StandBy on a nightstand becomes actually useful.",
      why: "Needs a low-power LTPO panel. 14 Pro started it; iPhone 17 brought it to the non-Pro (Air too). 60Hz phones cannot do this.",
      has: (p) => p.alwaysOn,
    },
    {
      id: "dynamic-island",
      name: "Dynamic Island",
      category: "display",
      icon: "fa-ellipsis",
      weight: 56,
      blurb: "Timers, maps, calls, and Now Playing live in the pill at the top instead of banners that cover what you’re doing.",
      why: "The hardware cutout changed on 14 Pro and every 15 / 16 / 17 except the e models, which still use a notch.",
      has: (p) => p.face === "island",
    },
    {
      id: "ceramic-shield-2",
      name: "Ceramic Shield 2",
      category: "display",
      icon: "fa-shield",
      weight: 46,
      blurb: "The iPhone 17 front glass is rated for much better scratch resistance than the Ceramic Shield that started on iPhone 12.",
      why: "New cover-glass formula on the iPhone 17 family, including 17e and Air.",
      has: (p) => p.ceramicShield >= 2,
    },
    {
      id: "ceramic-shield",
      name: "Ceramic Shield front",
      category: "display",
      icon: "fa-shield",
      weight: 40,
      blurb: "Tougher front glass than the pre-12 iPhones. Drops onto concrete are still drops, but the screen survives more of them.",
      why: "Material change starting with iPhone 12. iPhone 8 through 11 and the first SE years don’t have it.",
      has: (p) => p.ceramicShield >= 1,
    },
    {
      id: "face-id",
      name: "Face ID",
      category: "controls",
      icon: "fa-user-lock",
      weight: 61,
      blurb: "Unlock, Apple Pay, and app passwords with a glance. No Home button, and it works with a mask on newer iOS versions.",
      why: "TrueDepth camera system. SE and iPhone 8 still use Touch ID in the Home button.",
      has: (p) => p.faceId,
    },
    {
      id: "action-button",
      name: "Action button",
      category: "controls",
      icon: "fa-circle-pause",
      weight: 71,
      blurb: "The old ring/silent switch becomes a programmable key: silent, Focus, camera, Visual Intelligence, shortcut, or accessibility.",
      why: "A different physical button, from 15 Pro and every 16 / 17. iPhone 15 and older still have a mute switch.",
      has: (p) => p.actionButton,
    },
    {
      id: "usb-c",
      name: "USB-C",
      category: "controls",
      icon: "fa-plug",
      weight: 73,
      blurb: "Same cable as your laptop, iPad, and earbuds. On Pro models, USB 3 also dumps photos and video onto a drive much faster.",
      why: "The port changed on iPhone 15. Everything before is Lightning.",
      has: (p) => p.connector === "USB-C",
    },
    {
      id: "usb-3",
      name: "USB 3 transfer speeds",
      category: "controls",
      icon: "fa-bolt",
      weight: 36,
      blurb: "Offload ProRes and 48MP bursts at USB 3 speeds instead of waiting on USB 2. Needs a USB 3 cable.",
      why: "Controller and port wiring on 15 Pro, 16 Pro, and 17 Pro. USB-C on non-Pro iPhones is still USB 2.",
      has: (p) => p.usb3,
    },
    {
      id: "magsafe",
      name: "MagSafe",
      category: "controls",
      icon: "fa-magnet",
      weight: 49,
      blurb: "Snap-on charging, wallets, and stands that actually line up. Also enables a lot of third-party mounts.",
      why: "Magnet array and charging coil added on iPhone 12. 8, X, 11, and SE don’t have it.",
      has: (p) => p.magsafe,
    },
    {
      id: "5g",
      name: "5G",
      category: "connectivity",
      icon: "fa-signal",
      weight: 67,
      blurb: "Faster downloads and more consistent service in cities that have moved on from LTE. Also required for some carrier features.",
      why: "A 5G modem. iPhone 12 and later (plus SE 2022) have it. 11 and older are LTE-only.",
      has: (p) => p.fiveG,
    },
    {
      id: "wifi-7",
      name: "Wi-Fi 7",
      category: "connectivity",
      icon: "fa-wifi",
      weight: 38,
      blurb: "Lower latency and more headroom on a modern router. It is noticeable for large iCloud Photo Library syncs and spatial video.",
      why: "New radio. iPhone 16 (not 16e) and iPhone 17 (not 17e) include it; 17 also adds Apple’s N1 wireless chip.",
      has: (p) => p.wifi >= 7,
    },
    {
      id: "uwb",
      name: "Ultra Wideband / Precision Finding",
      category: "connectivity",
      icon: "fa-location-crosshairs",
      weight: 42,
      blurb: "Directional arrows to an AirTag, Precision Finding for friends, and extras like sharing a Keynote by holding two iPhones together.",
      why: "U1 arrived on iPhone 11; a second-gen chip is on 15 Pro and most 16 / 17 models. 16e and 17e skip UWB.",
      has: (p) => p.uwb >= 1,
    },
    {
      id: "thread",
      name: "Thread (smart home)",
      category: "connectivity",
      icon: "fa-house-signal",
      weight: 34,
      blurb: "Your iPhone can talk Thread for Matter accessories (locks, bulbs, and hubs) without a separate border router in some setups.",
      why: "A Thread radio, starting with 15 Pro and continuing on most 16 / 17 phones (not the e models).",
      has: (p) => p.thread,
    },
    {
      id: "crash-detection",
      name: "Crash Detection",
      category: "safety",
      icon: "fa-car-burst",
      weight: 69,
      blurb: "If the phone thinks you’ve been in a severe car crash, it can call emergency services and share your location.",
      why: "New motion-sensing fusion on iPhone 14 and later. You cannot add this with an iOS update on 13 or older.",
      has: (p) => p.crashDetection,
    },
    {
      id: "satellite-sos",
      name: "Emergency SOS via satellite",
      category: "safety",
      icon: "fa-satellite",
      weight: 77,
      blurb: "Text emergency services when there’s no cellular or Wi-Fi: hiking, parking garages, rural roads.",
      why: "Custom antenna and modem work that started with iPhone 14. Older phones have no satellite radio.",
      has: (p) => p.satelliteSos,
    },
    {
      id: "satellite-messages",
      name: "Messages via satellite",
      category: "safety",
      icon: "fa-comment-sms",
      weight: 59,
      blurb: "Send iMessages or texts over satellite when you’re off the grid, not only to 911.",
      why: "Same satellite hardware as Emergency SOS (iPhone 14 and later), unlocked in later iOS releases.",
      has: (p) => p.satelliteMessages,
    },
    {
      id: "roadside-satellite",
      name: "Roadside Assistance via satellite",
      category: "safety",
      icon: "fa-car",
      weight: 47,
      blurb: "Request roadside help through satellite if your car dies somewhere with no bars.",
      why: "Satellite-capable iPhones (14 and later).",
      has: (p) => p.roadsideSatellite,
    },
    {
      id: "mie",
      name: "Memory Integrity Enforcement",
      category: "security",
      icon: "fa-shield-halved",
      weight: 53,
      blurb: "Hardware-backed memory tagging that makes a whole class of spyware-style exploits much harder. You never see it; it just raises the cost of an attack.",
      why: "A19-generation security. Apple enabled it on the iPhone 17 family.",
      has: (p) => p.mie,
    },
    {
      id: "variable-aperture",
      name: "Variable-aperture Fusion camera",
      category: "camera",
      icon: "fa-camera",
      weight: 91,
      blurb: "The 48MP main camera can open up for low light or stop down for deeper focus, the kind of control that used to mean a real lens ring.",
      why: "New main-camera hardware on iPhone 18 Pro and 18 Pro Max. No software update adds this to iPhone 17 Pro.",
      has: (p) => p.variableAperture,
    },
    {
      id: "photographic-styles-3",
      name: "Photographic Styles with texture and grain",
      category: "camera",
      icon: "fa-sliders",
      weight: 57,
      blurb: "The third-generation styles let you dial texture and grain while you shoot, so a roll looks like your taste instead of a filter later.",
      why: "A camera pipeline Apple shipped with iPhone 18 Pro and iPhone Duo.",
      has: (p) => p.photographicStyles >= 3,
    },
    {
      id: "dual-neural",
      name: "Dual 16-core Neural Engine",
      category: "intelligence",
      icon: "fa-microchip",
      weight: 75,
      blurb: "Twice the on-device AI compute of last year’s Pro chips. Siri AI and camera models stay on the phone more often, and stay faster.",
      why: "A20 Pro silicon. iPhone 18 Pro, 18 Pro Max, and iPhone Duo.",
      has: (p) => p.dualNeural,
    },
    {
      id: "foldable",
      name: "Foldable design",
      category: "display",
      icon: "fa-tablet-screen-button",
      weight: 99,
      blurb: "Opens to a 7.6-inch canvas, Apple’s largest iPhone display, and closes to a pocketable 5.4-inch phone. Same aspect ratio, both sides.",
      why: "iPhone Duo is the first foldable iPhone. No slab iPhone can do this.",
      has: (p) => p.foldable,
    },
    {
      id: "dual-display",
      name: "Inner and outer Super Retina displays",
      category: "display",
      icon: "fa-clone",
      weight: 89,
      blurb: "Use the outer display one-handed, then open for movies, two apps, or a notebook. Both panels are ProMotion, Always-On, and 3000 nits.",
      why: "The Duo hinge and two OLED panels. Unique to iPhone Duo.",
      has: (p) => p.dualDisplay,
    },
    {
      id: "nano-texture",
      name: "Nano-texture inner display",
      category: "display",
      icon: "fa-sun",
      weight: 63,
      blurb: "A matte finish that cuts glare and helps hide the crease. It is built for viewing in bright rooms, not just a software dimmer.",
      why: "A physical finish on Duo’s inner display.",
      has: (p) => p.nanoTexture,
    },
    {
      id: "split-apps",
      name: "Two apps, side by side",
      category: "display",
      icon: "fa-table-columns",
      weight: 81,
      blurb: "iOS 27 on Duo puts two apps on the inner display at once (mail and a map, notes and a browser), like iPad, in your pocket.",
      why: "Needs the inner canvas. iPhone Duo only.",
      has: (p) => p.splitApps,
    },
    {
      id: "smart-take",
      name: "Smart Take",
      category: "camera",
      icon: "fa-wand-magic-sparkles",
      weight: 79,
      blurb: "On-device models watch the scene and fire when people are actually posing, so you’re in the photo, not stuck behind the shutter.",
      why: "Uses Duo’s fold + A20 Pro. Not available on a single-display iPhone.",
      has: (p) => p.smartTake,
    },
    {
      id: "duo-preview",
      name: "Duo Preview & Kid Cue",
      category: "camera",
      icon: "fa-children",
      weight: 72,
      blurb: "Whoever you’re photographing sees a live preview on the outer display. Kid Cue plays a Peanuts animation so little kids look at the lens.",
      why: "Needs a second outward-facing screen. iPhone Duo only.",
      has: (p) => p.duoPreview,
    },
    {
      id: "under-display-cam",
      name: "Under-display FaceTime camera",
      category: "camera",
      icon: "fa-video",
      weight: 58,
      blurb: "The inner display stays uninterrupted until you need a camera. Then a FaceTime camera appears beneath the glass.",
      why: "Hardware under Duo’s inner panel.",
      has: (p) => p.underDisplayCam,
    },
    {
      id: "apple-pencil",
      name: "Apple Pencil on iPhone",
      category: "controls",
      icon: "fa-pencil",
      weight: 65,
      blurb: "Notes, sketches, and markups on either Duo display with Apple Pencil (USB-C).",
      why: "Duo’s inner display and iOS 27 pencil path. Slab iPhones don’t take Pencil.",
      has: (p) => p.applePencil,
    },
    {
      id: "ceramic-back",
      name: "Ceramic Shield back",
      category: "display",
      icon: "fa-shield",
      weight: 45,
      blurb: "The back glass is Ceramic Shield too, not just the front, so pocket keys are less of a lottery.",
      why: "iPhone 18 Pro models and iPhone Duo. Earlier iPhones use standard back glass.",
      has: (p) => p.ceramicBack,
    },
  ];

  const IOS_FEATURES = [
    {
      minIos: 17,
      name: "StandBy",
      blurb: "Flip iPhone on its side while charging and it becomes a clock, photos, or widgets. Always-On phones keep it visible the whole time.",
    },
    {
      minIos: 17,
      name: "Interactive widgets & Lock Screen",
      blurb: "Widgets you can tap without opening the app, plus a fully customizable Lock Screen with layered photos.",
    },
    {
      minIos: 17,
      name: "NameDrop & improved AirDrop",
      blurb: "Hold two iPhones together to exchange contacts, or start an AirDrop without hunting through Control Center.",
    },
    {
      minIos: 18,
      name: "RCS in Messages",
      blurb: "Typing indicators, read receipts, and higher-quality media when you text Android. The green bubble got less painful.",
    },
    {
      minIos: 18,
      name: "Journal app",
      blurb: "A first-party journal that can suggest moments from photos, workouts, and places.",
    },
    {
      minIos: 18,
      name: "Control Center overhaul",
      blurb: "Resizable, multi-page controls you can rearrange, including a dedicated now-playing and Home page.",
    },
    {
      minIos: 18,
      name: "Photos redesign",
      blurb: "A single Photos view with collections, groups, and a filter bar instead of the old tab maze.",
    },
    {
      minIos: 26,
      name: "Liquid Glass design",
      blurb: "The iOS 26 look: clearer layers, new materials, and refreshed system apps. Holdout phones stuck on iOS 18 never get it.",
    },
    {
      minIos: 26,
      name: "Call Screening",
      blurb: "Unknown callers can be asked what they want before the phone rings at you.",
    },
    {
      minIos: 27,
      name: "Siri AI on iOS 27",
      blurb: "A more capable, personal Siri that can use your context, on phones that also have Apple Intelligence hardware.",
    },
  ];

  global.LEAP_DATA = { PHONES, FEATURES, CATEGORIES, IOS_FEATURES, IMAGES, MARKETING, FEATURE_IMAGES, PRODUCT_PAIR, PRODUCT_PAD, PRODUCT_FAR, PRODUCT_TIGHT };
})(window);
